version: '3.8'

services:
  postgres:
    image: postgres-node
    build: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5